### ISSUE TITLE
Automatic kernel selection

### ISSUE THREAD

**Issue by glass-ships** [det-lab/jupyterhub-deploy-kubernetes-jetstream#27]
I'm wondering if it would be at all possible to configure the jupyter notebooks to open with the most recent cdms kernel by default? 

This may possibly be related to an email I just sent regarding the possibility of running `install_cdms_kernels` during the image spawning process.

**Comment by zonca** [comment]
I tried to have it running automatically, as a before-notebook hook,
it is actually still configured for that, see https://github.com/zonca/docker-jupyter-cdms-light/blob/master/Dockerfile

However I couldn't get it to run. Let's keep this issue open, I'll try again.

About automatic kernel selection, I don't know if that is possible, anyway it seems unrelated to the deployment on Jetstream, so if someone wants to investigate that and provide a solution, I'm happy to install it.

**Comment by zonca** [comment]
running the `install_cdms_kernels` script is quite slow, because it also overwrites the old kernels.
so I think it is better to keep it running manually,
the documentation for the users on how to manage their kernels is at https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream/#install-jupyter-kernels

If anyone has a better idea, let's reopen the issue

**Comment by zonca** [comment]
in case we need to revisit this issue in the future, another option is to use `lifecyclehooks` in the zero to jupyterhub configuration.

See https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream/blob/246e5c684776b31f5c2db636af2fcd44e01fa670/config_standard_storage.yaml#L75-L86
