### ISSUE TITLE
All but 2 nodes are unavailable

### ISSUE THREAD

**Issue by zkromerUCD** [det-lab/jupyterhub-deploy-kubernetes-jetstream#55]
When trying to start with a default server configuration, I get this error, and the loading for the server stalls:
2021-03-18T00:02:34.528016Z [Warning] 0/2 nodes are available: 2 Insufficient cpu.

Amy checked the admin panel, and nobody else seems to be using any nodes.

**Comment by zonca** [comment]
yes, sorry, I didn't realize that the medium instances that we are using now to save resources have only 6 CPUs and I was requesting 5 of them for the "Default" configuration.
This is the reason for this error.
Now I have setup the Default configuration to have only 2 CPU which are guaranteed, but the limit is 6 CPUs, so that if there is extra availability, your pod can use it.
So this should be fixed now. 

So now we should be able to fit 2 users per node, for a total of 4 users using the default configuration using 5 GB and 2-6 CPUs. And twice that in the Tiny configuration.

@pibion Do you think it would be useful to have a "Medium" configuration with 10GB of RAM and 4 CPUs?

**Comment by zonca** [comment]
See the current configuration in:

https://github.com/det-lab/jupyterhub-deploy-kubernetes-jetstream/blob/37a8d0acffa41a9b62016549973446abe96a5c2c/config_standard_storage.yaml#L30-L51
