### ISSUE TITLE
Unable to access XSEDE Resources

### ISSUE THREAD

**Issue by thathayhaykid** [det-lab/jupyterhub-deploy-kubernetes-jetstream#59]
Hi There!

I'm coming across an error trying to access the XSEDE Jupyter hub resource! I was trying to access the 'default' setting,
A colleague of mind is experiencing the same issue!

Amy tried out the Tiny setting and it worked for her!

Here's a screenshot with the error that's happening!

Please let me know if there's anything else I can provide you with to help!

Thanks.

-Haythem

![MansourHaythem_ErrorMEssage](https://user-images.githubusercontent.com/12423317/141345775-0c829c53-cf92-4c60-9218-3b2ae9eb4434.png)

**Comment by zonca** [comment]
@thathayhaykid in order to save resources as usage was low, I had downsized to only 1 medium instance.
I deployed another service (@pibion it was ServiceX) that was consuming a lot of ram so you only could have 1 session running.
Now I terminated that service, I will launch it only during testing.

So, now I have reconfigured the options given the available RAM:

* with tiny you have 3 GB and you can run up to 4 users at the same time
* default is now 6 GB instead of 5 and you can have 2 concurrent users
* full-node just 1 user but you have 12 GB

@pibion if needed we can scale it up and get a larger instance, but first you need to check how much time we have left in the allocation
